# Continuous integration for Linux and Windows.
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux-stub:
      platform: 'Linux-Stub'
      imageName: 'ubuntu-latest'
      cmakeArgs: '-g ''Linux Makefiles'' -DQUIC_TLS=stub -DQUIC_ENABLE_LOGGING=off'
      testCmd: 'artifacts/bin/quicattack -type:2 -ip:138.91.188.147:4444 -timeout:30000'
    windows-x64-stub:
      platform: 'Windows-x64-Stub'
      imageName: 'windows-latest'
      cmakeArgs: '-g ''Visual Studio 16 2019'' -A x64 -DQUIC_TLS=stub -DQUIC_ENABLE_LOGGING=off'
      testCmd: 'artifacts\bin\release\quicattack.exe -type:2 -ip:138.91.188.147:4444 -timeout:30000'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  submodules: recursive
  persistCredentials: true

- task: CMake@1
  displayName: 'CMake Generator'
  inputs:
    cmakeArgs: '$(cmakeArgs) ..'

- task: CMake@1
  displayName: 'CMake Build'
  inputs:
    cmakeArgs: '--build . --config RELEASE'

- task: CmdLine@2
  displayName: 'Run Tests'
  timeoutInMinutes: 10
  inputs:
    script: '$(testCmd)'
